image: raplonu/domo:1.0

stages:
    - build
    - test

build_release:
    stage: build
    script:
        - conan build . -b missing
    when: manual
    artifacts:
        paths:
        - public

build_release_always:
    stage: build
    extends: build_release
    when: always
    only:
        - main
        - rc
        - tags
        - merge_requests
        - develop
